//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentImage
    {
        public int CommentImageID { get; set; }
        public System.Guid ImageID { get; set; }
        public System.Guid CommentID { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Image Image { get; set; }
    }
}
